### PR TITLE
Fix/various bugs issue672

### LINKED ISSUE #672: Bugs - comments & newsletter registration
## Issue Type

**Bug fix**

## Description
[reactBugs2.docx](https://github.com/Haaretz/htz-frontend/files/2240327/reactBugs2.docx)

### PR DESCRIPTION
**Pull request by kedarguy**
closes #672

### CODE REVIEW

File: packages/components/htz-components/src/components/ActionButtons/actionList.js [hunk 1]
```diff
@@ -403,6 +403,7 @@ const Print = ({ buttonStyles, size, iconStyles, ...props }) => (
       <Button
         {...props}
         miscStyles={buttonStyles}
+        target="_blank"
         href={`http://${hostname}/misc/article-print-page/${articleId}`}
```
Comment (kedarguy) [inline packages/components/htz-components/src/components/ActionButtons/actionList.js]: change to attrs

File: packages/components/htz-components/src/components/Button/Button.js [hunk 2]
```diff
@@ -107,6 +107,8 @@ Button.propTypes = {
   prefetch: PropTypes.bool,
   /** The HTML tag to render the `<Button />` as */
   tagName: PropTypes.string,
+  /** Simple HTML target (only relevant when `href` prop is defined) */
```
Comment (kedarguy) [inline packages/components/htz-components/src/components/Button/Button.js]: remove target prop

File: packages/components/htz-components/src/components/Newsletter/NewsletterWithoutApollo.js [hunk 3]
```diff
@@ -99,7 +102,8 @@ export default class NewsletterWithoutApollo extends React.Component {
       this.setState({
         id:
           this.props.id ||
-          `newsletterRegForm${Math.round(Math.random() * 1000000)}`,
+          `newsletterRegForm${this.props.contentId ||
+            Math.round(Math.random() * 1000000)}`,
```
Comment (kedarguy) [inline packages/components/htz-components/src/components/Newsletter/NewsletterWithoutApollo.js]: remove random
